### ISSUE TITLE
Support for Rook/Ceph storage provisioner

### ISSUE THREAD

**Issue by asoltesz** [asoltesz/solakube#6]
The Hetzner virtual machines currently have a lot of unused storage on them after provisioned (e.g.: cx31, 80 GB of storage, used: less than 15 GB).

Since we use >= 3 machines, Ceph could be used for providing HA storage over the SSD disks visible for the VMs.

Also, since Hetzner Cloud Volumes are not snapshottable, it would be nice to have a storage type that can be backed up via volume snapshotting while the application is online and under load.

Develop easy deployment of Rook/Ceph in order to utilize this storage.

- [X] Deploy scripts
- [X] Add Cloud-Init scripts configurable for the Terraform module for repartitioning node VM disk
- [X] Disk partitions arranged so that sda2 can be presented to Rook/Ceph as storage space
- [x] Test memory/CPU usage with light / medium load (e.g. Nextcloud file uploads)
- [ ] Make OSD container resource requests / limits configurable
- [x] Implement default resource requests
- [X] Documentation

**Comment by bratao** [comment]
@asoltesz first of all, thank you for providing those scripts. They saved me a lot of time. Do you plan to finish this feature anytime soon?

**Comment by asoltesz** [comment]
@bratao I believe there is a working version on the "develop" branch. 

Unfortunately, it seems that there is no way to automatically create Hetzner VMs with custom partitioning, so Ceph can only operate over a folder (as opposed to clean partition/device) which is only acceptable for "testing" in the view of the Ceph people (they are probably right, still, it is fairly annoying).

Please bugger the Hetzner people for custom partitioning, maybe they will implement it if enough people comes to them with this issue.

Also, I happily accept proposals for dynamic re-partitioning after VM creation (if it is possible at all).

**Comment by bratao** [comment]
Ah, I see. Thank you!

**Comment by asoltesz** [comment]
A possible way to partition the Hetzner VMs is using the user_data attribute in the API which should be a Cloud-Init script.

Sample taken from here: https://gist.github.com/ctron/88fa70926fc14c894e42ecf373cb271e

The user_data segment in YAML: 

```
#cloud-config

# we need to disable the initial call to "growpart" as otherwise the first partition would consume
# all space on the dist
#
# The final disk layout is:
# #0    0 - 10GB - ext4 on /
# #1 10GB - 100% - lvm
#
# The reason for this approach is that when using CentOS on Hetzner you cannot use
# the "disk_setup" mechanism from cloud-init, it simply is ignored.

growpart:
  mode: off

runcmd:
  - [ parted, "/dev/sda", mkpart, primary, ext2, "10GB", "100%" ]  # create a new partition, starting at 10GB
  - [ parted, "/dev/sda", set, "2", lvm, on ]  # set LVM flag
  - [ growpart, "/dev/sda", "1" ]  # grow first partition to 10GB
  - [ partx, --update, "/dev/sda" ] # reload partition table
  - [ resize2fs, /dev/sda1 ] # resize first partition (/) to 10GB
  - [ pvcreate, "/dev/sda2" ] # create PV on /dev/sda2 (100%-10GB)
  - [ vgcreate, vg1, "/dev/sda2" ] # create VG, adding PV /dev/sda2

repo_update: true
repo_upgrade: all

packages:
  - lvm2  # missing in the Hetzner image
``` 

When using the API, this may need to be in JSON.

The format and commands are described in detail on the Cloud-Init docs (https://cloudinit.readthedocs.io/en/latest)

I have manually tested (Cloud Console) the above sample on a CX11 / Centos 7 instance and seems to work properly (lsblk shows both partition after the VM becomes accessible).

**Comment by asoltesz** [comment]
This is mostly implemented in develop.

The only remaining part is setting proper resources to the OSD pods in the storage cluster config.
